language: smalltalk
sudo: false

os:
- linux
- osx

smalltalk:
- Pharo-7.0
- Pharo64-7.0
- Pharo-6.1
- Pharo64-6.1

env:
  - JOB=test
  - JOB=sync-wiki

#Exclude all jobs but one so sync-wiki is executed only once
matrix:
  exclude:
    - os: osx
      env: JOB=sync-wiki
    - os: linux
      smalltalk: Pharo-70
      env: JOB=sync-wiki
    - os: linux
      smalltalk: Pharo-61
      env: JOB=sync-wiki
    - os: linux
      smalltalk: Pharo64-61
      env: JOB=sync-wiki
      


before_install:
  - eval "$(ssh-agent)"
  - ssh-keyscan github.com >> ~/.ssh/known_hosts

script:
  - if [[ ${JOB} == "test" ]]; then "$SMALLTALK_CI_HOME/run.sh"; fi
  - if [[ ${JOB} == "sync-wiki" && ${TRAVIS_BRANCH} == "master" ]]; then ./scripts/sync-wiki.sh; fi