language: smalltalk
sudo: false

os:
- linux
- osx

smalltalk:
- Pharo-7.0
- Pharo64-7.0
- Pharo-6.1
- Pharo64-6.1

env:
  matrix:
    - CI_FILE=.smalltalk.ston
    - CI_FILE=.smalltalk.metacellotests.ston

before_install:
- eval "$(ssh-agent)"
- ssh-keyscan github.com >> ~/.ssh/known_hosts

script:
- travis_wait 120 sleep infinity &
- if [ $CI_FILE -ne ".updatingIceberg.ston" ]; then
  $SMALLTALK_CI_HOME/run.sh ${CI_FILE} ; fi
