name: Run All Tests

on:
  push:
    branches: [ dev-1.9 ]
    paths-ignore:
    - 'README.md'
    - 'docs/**'
  pull_request:
    branches: [ dev-1.9 ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-9.0 ]
        os: [ ubuntu-latest, macos-latest ]
        ston: [ .smalltalk.ston ]
        include:
          - smalltalk: Pharo64-9.0
            os: windows-latest
            ston: .smalltalk.no.metacellotests.ston
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }} with ${{ matrix.ston }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        shell: bash
        timeout-minutes: 30
