name: Update

on:
  push:
    branches: [ dev-1.9 ]
  pull_request:
    branches: [ dev-1.9 ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: scripts/testUpdateIceberg.sh
        shell: bash
        timeout-minutes: 15
